name: publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    if: ${{ github.repository_owner == 'maxmilton' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun run build
      - run: bun run lint
      - run: bun run test
      - run: zip -jv chrome-extension.zip dist/*
      - uses: actions/attest-build-provenance@0f67c3f4856b2e3261c31976d6725780e5e4c373 # v4
        with:
          subject-path: chrome-extension.zip
      - run: gh release create "${{ github.ref_name }}" chrome-extension.zip --draft --generate-notes
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
